fixes #138
GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter pull request #139
Opened 2022-02-20 05:00 UTC by jasonklotzer

2022-02-22 14:46 UTC, jasonklotzer commented
/gcbrun

2022-02-22 15:15 UTC, danielbeaudreau requested changes
Thanks for the contribution.

2022-02-25 22:14 UTC, jasonklotzer commented on import/src/main/java/com/google/cloud/healthcare/imaging/dicomadapter/ImportAdapter.java
>      if (flags.useHttp2ForStow) {
Yes, no HTTP2 being used by this user.

2022-02-25 22:15 UTC, jasonklotzer commented
Closing and moving this PR to a native branch with updates.

2022-02-25 22:15 UTC, closed without merging